spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          naver:
            client-id: uvxeeIjVjXJ0T_7Q8Qr4
            client-secret: Y_Fu5r8Y1m
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - nickname
  servlet:
    multipart:
      # 개별 파일의 크기 제한
      max-file-size: 10MB
      # 전체 총 요청 크기 제한
      max-request-size: 20MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: iAxixh53UL,u]Znp!=]>k#7z#T~x!ne%w2#p2qk+4yHne71-gLhP*q%Fm
